// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_p3qEO5cI4Q5vuBT26TUlvZWbknf7l0',
    appId: '1:1012002553722:ios:217c90b2673f46e41060c3',
    messagingSenderId: '1012002553722',
    projectId: 'capstone-6f53b',
    storageBucket: 'capstone-6f53b.firebasestorage.app',
    iosBundleId: 'com.example.studentPerformanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC448qdQCcB4x1eUDDwO4_BKAzLLCIxGUs',
    appId: '1:328417677942:ios:47c5ff43b5a1ee78004557',
    messagingSenderId: '328417677942',
    projectId: 'student-performance-app-11723',
    storageBucket: 'student-performance-app-11723.firebasestorage.app',
    iosBundleId: 'com.example.studentPerformanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJtC2lwS9zanfbfOpbXNSeDTWQq87K21A',
    appId: '1:328417677942:web:815bd60e5062b5f5004557',
    messagingSenderId: '328417677942',
    projectId: 'student-performance-app-11723',
    authDomain: 'student-performance-app-11723.firebaseapp.com',
    storageBucket: 'student-performance-app-11723.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfsjmeXx2CIs89AivtZRfwyQiY1_lYO24',
    appId: '1:1012002553722:web:57e82a7ecd13f3c71060c3',
    messagingSenderId: '1012002553722',
    projectId: 'capstone-6f53b',
    authDomain: 'capstone-6f53b.firebaseapp.com',
    storageBucket: 'capstone-6f53b.firebasestorage.app',
    measurementId: 'G-NBX52WZ4R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdvw7_qbuX9qqokns5mhhGEWXH__WPQ0',
    appId: '1:1012002553722:android:fcd660e81d6366151060c3',
    messagingSenderId: '1012002553722',
    projectId: 'capstone-6f53b',
    storageBucket: 'capstone-6f53b.firebasestorage.app',
  );

}